// Generated by CoffeeScript 1.7.1
(function() {
  var expect, superagent;

  superagent = require('superagent');

  expect = require('expect.js');

  describe('stutz survey api', function() {
    it('post object', function(done) {
      return superagent.post('http://localhost:3000/surveys/test').send({
        name: 'Stutz',
        email: 'stutz@stutzsolucoes.com.br'
      }).end(function(e, res) {
        var id;
        expect(e).to.eql(null);
        expect(res.body.length).to.eql(1);
        expect(res.body[0]._id.length).to.eql(24);
        id = res.body[0]._id;
        return done();
      });
    });
    it('retrieves an object', function(done) {
      return superagent.get('http://localhost:3000/surveys/test/' + id).end(function(e, res) {
        expect(e).to.eql(null);
        expect(typeof res.body).to.eql('object');
        expect(res.body._id.length).to.eql(24);
        expect(res.body._id).to.eql(id);
        return done();
      });
    });
    it('retrieves a collection', function(done) {
      superagent.get('http://localhost:3000/surveys/test').end(function(e, res) {
        expect(e).to.eql(null);
        expect(res.body.length).to.be.above(0);
        return expect(res.body.map(function(item) {
          return item._id;
        })).to.contain(id);
      });
      return done();
    });
    it('updates an object', function(done) {
      return superagent.put('http://localhost:3000/surveys/test/' + id).send({
        name: 'New Stutz',
        email: 'new@stutzsolucoes.com.br'
      }).end(function(e, res) {
        expect(e).to.eql(null);
        expect(typeof res.body).to.eql('object');
        expect(res.body.msg).to.eql('success');
        return done();
      });
    });
    it('checks an updated object', function(done) {
      return superagent.get('http://localhost:3000/surveys/test/' + id).end(function(e, res) {
        expect(e).to.eql(null);
        expect(typeof res.body).to.eql('object');
        expect(res.body._id.length).to.eql(24);
        expect(res.body._id).to.eql(id);
        return expect(res.body.name).to.eql('New Stutz');
      });
    });
    return it('removes an object', function(done) {
      return superagent.del('http://localhost:3000/surveys/test/').end(function(e, res) {
        expect(e).to.eql(null);
        expect(typeof res.body).to.eql('object');
        expect(res.body.msg).to.eql('success');
        return done();
      });
    });
  });

}).call(this);
